### ISSUE TITLE
How to pass our own HTML

### ISSUE THREAD

**Issue by amrit42087** [insanoid/iOS-HTMLTextEditor#12]
The demo.html gets loaded in webview. But its pre filled with "Content goes here..." How to I pre fill it with my own HTML

**Comment by amrit42087** [comment]
`-(void)webViewDidFinishLoad:(UIWebView *)webView{

```
[self.webView stringByEvaluatingJavaScriptFromString:
 @"document.body.style.margin='0';document.body.style.padding = '0'"];
[self.webView stringByEvaluatingJavaScriptFromString:
 @"document.getElementById('editor').innerHTML='<b>'Hello</b> <i>World</i>!';"];
[self.webView stringByEvaluatingJavaScriptFromString:
 @"document.getElementById('editor').focus();"];
```

}
`
When this code runs, the editor should show "**Hello** _World_" but it still says, "Content goes here...

**Comment by insanoid** [comment]
See https://github.com/insanoid/iOS-HTMLTextEditor/issues/6. 

Your HTML is wrong. `<b>&#39;Hello…` for `<b>'Hello…".`
